name: jsdeals
on: 
#  push:
#    branches: 
#      - master
#    paths:
#      - 'js/dev/*'
  schedule:
    - cron: '0 7 * * 1'

jobs:
  push_jsdeals:
    runs-on: ubuntu-latest
    name: Minify ES6+ JS files
    steps:
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
      timeout-minutes: 1
    - name: Install UglifyJS-ES
      run: npm install uglify-es -g
